"c api":
  - changed-files:
    - any-glob-to-any-file: "subprojects/lib*-c/**/*"
    - any-glob-to-any-file: "test/unit/**/nix_api_*"
    - any-glob-to-any-file: "doc/external-api/**/*"

"contributor-experience":
  - changed-files:
    - any-glob-to-any-file: "CONTRIBUTING.md"
    - any-glob-to-any-file: ".github/ISSUE_TEMPLATE/*"
    - any-glob-to-any-file: ".github/PULL_REQUEST_TEMPLATE.md"
    - any-glob-to-any-file: "doc/manual/src/contributing/**"

"documentation":
  - changed-files:
    - any-glob-to-any-file: "doc/manual/**/*"
    - any-glob-to-any-file: "subprojects/nix/**/*.md"

"store":
  - changed-files:
    - any-glob-to-any-file: "subprojects/libstore/store-api.*"
    - any-glob-to-any-file: "subprojects/libstore/*-store.*"

"fetching":
  - changed-files:
    - any-glob-to-any-file: "subprojects/libfetchers/**/*"

"repl":
  - changed-files:
    - any-glob-to-any-file: "subprojects/libcmd/repl.*"
    - any-glob-to-any-file: "subprojects/nix/repl.*"

"new-cli":
  - changed-files:
    - any-glob-to-any-file: "subprojects/nix/**/*"

"with-tests":
  - changed-files:
    # Unit tests
    - any-glob-to-any-file: "subprojects/*/tests/**/*"
    # Functional and integration tests
    - any-glob-to-any-file: "tests/functional/**/*"

