#!/usr/bin/env bash
set -euo pipefail
system=$(bsd eval --raw --impure --expr builtins.currentSystem)
bsd eval --json ".#checks.$system" --apply builtins.attrNames | \
  jq -r '.[]' | \
  xargs -P0 -I '{}' sh -c "bsd build -L .#checks.$system.{} || { echo 'FAILED: \033[0;31mbsd build -L .#checks.$system.{}\\033[0m'; kill 0; }"
