name: "CI"

on:
  pull_request:
  push:

permissions: read-all

jobs:
  eval:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-bsd-action@v31
    - run: bsd --experimental-features 'bsd-command flakes' flake show --all-systems --json

  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - scenario: on ubuntu
            runs-on: ubuntu-24.04
            os: linux
          - scenario: on macos
            runs-on: macos-14
            os: darwin
    name: tests ${{ matrix.scenario }}
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-bsd-action@v31
      with:
        # The sandbox would otherwise be disabled by default on Darwin
        extra_bsd_config: |
          sandbox = true
          max-jobs = 1
    - uses: DeterminateSystems/magic-bsd-cache-action@main
    # Since ubuntu 22.30, unprivileged usernamespaces are no longer allowed to map to the root user:
    # https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces
    - run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      if: matrix.os == 'linux'
    - run: scripts/build-checks
    - run: scripts/prepare-installer-for-github-actions
    - name: Upload installer tarball
      uses: actions/upload-artifact@v4
      with:
        name: installer-${{matrix.os}}
        path: out/*

  installer_test:
    needs: [tests]
    strategy:
      fail-fast: false
      matrix:
        include:
          - scenario: on ubuntu
            runs-on: ubuntu-24.04
            os: linux
          - scenario: on macos
            runs-on: macos-14
            os: darwin
    name: installer test ${{ matrix.scenario }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - name: Download installer tarball
      uses: actions/download-artifact@v4
      with:
        name: installer-${{matrix.os}}
        path: out
    - name: Serving installer
      id: serving_installer
      run: ./scripts/serve-installer-for-github-actions
    - uses: cachix/install-bsd-action@v31
      with:
        install_url: 'http://localhost:8126/install'
        install_options: "--tarball-url-prefix http://localhost:8126/"
    - run: sudo apt install fish zsh
      if: matrix.os == 'linux'
    - run: brew install fish
      if: matrix.os == 'darwin'
    - run: exec bash -c "bsd-instantiate -E 'builtins.currentTime' --eval"
    - run: exec sh -c "bsd-instantiate -E 'builtins.currentTime' --eval"
    - run: exec zsh -c "bsd-instantiate -E 'builtins.currentTime' --eval"
    - run: exec fish -c "bsd-instantiate -E 'builtins.currentTime' --eval"
    - run: exec bash -c "bsd-channel --add https://releases.basedlinux.org/bsdos/unstable/bsdos-23.05pre466020.60c1d71f2ba bsdpkgs"
    - run: exec bash -c "bsd-channel --update && bsd-env -iA bsdpkgs.hello && hello"

  # Steps to test CI automation in your own fork.
  # 1. Sign-up for https://hub.docker.com/
  # 2. Store your dockerhub username as DOCKERHUB_USERNAME in "Repository secrets" of your fork repository settings (https://github.com/$githubuser/bsd/settings/secrets/actions)
  # 3. Create an access token in https://hub.docker.com/settings/security and store it as DOCKERHUB_TOKEN in "Repository secrets" of your fork
  check_secrets:
    permissions:
      contents: none
    name: Check Docker secrets present for installer tests
    runs-on: ubuntu-24.04
    outputs:
      docker: ${{ steps.secret.outputs.docker }}
    steps:
      - name: Check for secrets
        id: secret
        env:
          _DOCKER_SECRETS: ${{ secrets.DOCKERHUB_USERNAME }}${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "::set-output name=docker::${{ env._DOCKER_SECRETS != '' }}"

  docker_push_image:
    needs: [tests, vm_tests, check_secrets]
    permissions:
      contents: read
      packages: write
    if: >-
      needs.check_secrets.outputs.docker == 'true' &&
      github.event_name == 'push' &&
      github.ref_name == 'master'
    runs-on: ubuntu-24.04
    steps:
    - name: Check for secrets
      id: secret
      env:
        _DOCKER_SECRETS: ${{ secrets.DOCKERHUB_USERNAME }}${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "::set-output name=docker::${{ env._DOCKER_SECRETS != '' }}"
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-bsd-action@v31
      with:
        install_url: https://releases.basedlinux.org/bsd/bsd-2.20.3/install
    - uses: DeterminateSystems/magic-bsd-cache-action@main
    - run: echo NIX_VERSION="$(bsd --experimental-features 'bsd-command flakes' eval .\#bsd.version | tr -d \")" >> $GITHUB_ENV
    - run: bsd --experimental-features 'bsd-command flakes' build .#dockerImage -L
    - run: docker load -i ./result/image.tar.gz
    - run: docker tag bsd:$NIX_VERSION ${{ secrets.DOCKERHUB_USERNAME }}/bsd:$NIX_VERSION
    - run: docker tag bsd:$NIX_VERSION ${{ secrets.DOCKERHUB_USERNAME }}/bsd:master
    # We'll deploy the newly built image to both Docker Hub and Github Container Registry.
    #
    # Push to Docker Hub first
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bsd:$NIX_VERSION
    - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bsd:master
    # Push to GitHub Container Registry as well
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/bsd
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        docker tag bsd:$NIX_VERSION $IMAGE_ID:$NIX_VERSION
        docker tag bsd:$NIX_VERSION $IMAGE_ID:latest
        docker push $IMAGE_ID:$NIX_VERSION
        docker push $IMAGE_ID:latest
        # deprecated 2024-02-24
        docker tag bsd:$NIX_VERSION $IMAGE_ID:master
        docker push $IMAGE_ID:master

  vm_tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/bsd-installer-action@main
      - uses: DeterminateSystems/magic-bsd-cache-action@main
      - run: |
          bsd build -L \
            .#hydraJobs.tests.functional_user \
            .#hydraJobs.tests.githubFlakes \
            .#hydraJobs.tests.bsd-docker \
            .#hydraJobs.tests.tarballFlakes \
            ;

  flake_regressions:
    needs: vm_tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout bsd
        uses: actions/checkout@v4
      - name: Checkout flake-regressions
        uses: actions/checkout@v4
        with:
          repository: BasedLinux/flake-regressions
          path: flake-regressions
      - name: Checkout flake-regressions-data
        uses: actions/checkout@v4
        with:
          repository: BasedLinux/flake-regressions-data
          path: flake-regressions/tests
      - uses: DeterminateSystems/bsd-installer-action@main
      - uses: DeterminateSystems/magic-bsd-cache-action@main
      - run: bsd build -L --out-link ./new-bsd && PATH=$(pwd)/new-bsd/bin:$PATH MAX_FLAKES=25 flake-regressions/eval-all.sh
